### ISSUE TITLE
How to press ENTER key 

### ISSUE THREAD

**Issue by duvemula** [samick17/windows-automator-lib#3]
Hi @samick17,

I am unable to find ENTER key option from VK.
Could you please share me how to press the ENTER key with windows-automator-lib.

Regards,
Durga Prasad

**Comment by samick17** [comment]
Hi @duvemula ,

You can use following code to execute ENTER,
"**combinationKeyByVKValue**" can send composition key event at the same time

I name the "ENTER" key to "RETURN"
     
    require('windows-automator-lib').Core.combinationKeyByVKValue([VK.RETURN])

references: https://pc.net/helpcenter/answers/keyboard_return_key

Regards, 
Samick

**Comment by duvemula** [comment]
Thank you so much @samick17 for help
